
// src/lib/app-builder/flutter-gen/index.js

/**
 * Convert hex color to 0xFF...
 */
const toColor = (hex) => {
  if (!hex) return "0xFF000000";
  return "0xFF" + hex.replace("#", "");
};

/**
 * Generate pubspec.yaml
 */
const generatePubspec = (config) => {
  const packageName = config.name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  return `name: ${packageName}
description: Generated by WebsiteBuilder App Builder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  http: ^1.2.0
  share_plus: ^9.0.0
  supabase_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
`;
};

/**
 * Generate GitHub Action Workflow (Build APK)
 */
const generateWorkflow = (config) => {
  return `name: Build Android APK
on:
  push:
    branches:
      - build-artifacts
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true
      
      - run: |
          flutter create temp_app --project-name appbuilder_app --platforms android
          cp -r temp_app/android generated-app/
          rm -rf temp_app
          # Patch AndroidManifest with correct Label / Icon reference
          cp generated-app/android_xml_overlay/AndroidManifest.xml generated-app/android/app/src/main/AndroidManifest.xml

      - run: flutter pub get
        working-directory: ./generated-app

      - run: flutter build apk --release --no-tree-shake-icons
        working-directory: ./generated-app
      
      - name: Rename APK
        run: |
          APP_NAME=$(grep 'name:' generated-app/pubspec.yaml | cut -d ' ' -f 2)
          echo "App Name: $APP_NAME"
          mv generated-app/build/app/outputs/flutter-apk/app-release.apk generated-app/build/app/outputs/flutter-apk/$APP_NAME.apk
          echo "APK_PATH=generated-app/build/app/outputs/flutter-apk/$APP_NAME.apk" >> $GITHUB_ENV
          echo "APK_NAME=$APP_NAME.apk" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: \${{ env.APK_NAME }}
          path: \${{ env.APK_PATH }}
`;
};

const generateMain = (config, supabaseUrl, supabaseKey) => {
  const firstScreen = config.screens[0];
  const screenId = firstScreen.id;
  
  // Generate imports for all screens
  const imports = config.screens.map(s => 
      `import 'screens/${s.id}_screen.dart';` 
  ).join('\n');

  // Generate routes map
  let routes = config.screens.map(s => {
      const cls = s.id.charAt(0).toUpperCase() + s.id.slice(1) + 'Screen';
      return `'/${s.id}': (context) => const ${cls}(),`;
  }).join('\n        ');

  // Admin Routes
  if (config.adminPassword) {
      routes += `\n        '/admin_login': (context) => const AdminLoginScreen(),`;
      routes += `\n        '/admin_dashboard': (context) => const AdminDashboardScreen(),`;
  }

  return `import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'theme.dart';
${imports}
${config.adminPassword ? "import 'screens/admin_login_screen.dart';" : ""}
${config.adminPassword ? "import 'screens/admin_dashboard_screen.dart';" : ""}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await Supabase.initialize(
    url: '${supabaseUrl}',
    anonKey: '${supabaseKey}',
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${config.name}',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      initialRoute: '/${screenId}',
      routes: {
        ${routes}
      },
    );
  }
}
`;
};

/**
 * Generate lib/theme.dart
 */
const generateTheme = (config) => {
  const t = config.theme || {};
  return `import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class AppTheme {
  static const Color primary = Color(${toColor(t.primary_color)});
  static const Color secondary = Color(${toColor(t.secondary_color)});
  static const Color background = Color(${toColor(t.background_color)});
  static const Color surface = Color(${toColor(t.surface_color)});
  static const Color text = Color(${toColor(t.text_color)});

  static ThemeData get lightTheme => ThemeData(
    useMaterial3: true,
    scaffoldBackgroundColor: background,
    colorScheme: ColorScheme.light(
        primary: primary,
        secondary: secondary,
        surface: surface,
        onSurface: text,
    ),
    textTheme: GoogleFonts.${t.font_family?.toLowerCase() || 'inter'}TextTheme().apply(
        bodyColor: text,
        displayColor: text,
    ),
    appBarTheme: AppBarTheme(
        backgroundColor: surface,
        foregroundColor: text,
        elevation: 0,
    ),
    snackBarTheme: SnackBarThemeData(
      backgroundColor: primary,
      contentTextStyle: TextStyle(color: Colors.white),
      behavior: SnackBarBehavior.floating,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
    ),
    dialogTheme: DialogTheme(
      backgroundColor: surface, // Soothing background
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      titleTextStyle: TextStyle(color: text, fontSize: 20, fontWeight: FontWeight.bold),
      contentTextStyle: TextStyle(color: text.withOpacity(0.8), fontSize: 16),
    ),
  );
}
`;
};

/**
 * Render a single component to Dart code
 */
const renderComponent = (comp) => {
  const p = comp.props || {};
  
  switch(comp.type) {
    case 'text':
      return `Text(
        '${p.text}',
        style: TextStyle(
            fontSize: ${p.fontSize || 16},
            fontWeight: ${p.fontWeight === 'bold' ? 'FontWeight.bold' : 'FontWeight.normal'},
            color: ${p.color ? `Color(${toColor(p.color)})` : 'null'},
        ),
      ),SizedBox(height: 8),`;
      
    case 'button':
      // Connect onPressed to _handleAction
      const isAI = (p.action || "").startsWith('ai:');
      const childContent = isAI 
        ? `_loading ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : Text('${p.text}')`
        : `Text('${p.text}')`;

      return `SizedBox(
        width: ${p.fullWidth ? 'double.infinity' : 'null'},
        child: ElevatedButton(
            onPressed: ${isAI} && _loading ? null : () => _handleAction('${p.action || ""}'), 
            style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 14),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            ),
            child: ${childContent},
        ),
      ),SizedBox(height: 12),`;

    case 'hero': // Maps to Image
    case 'image':
      return `ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: Image.network(
            '${p.url}',
            height: ${p.height || 200},
            width: double.infinity,
            fit: BoxFit.cover,
            errorBuilder: (c,e,s) => Container(height: 200, color: Colors.grey[800]),
        ),
      ),SizedBox(height: 12),`;
      
    case 'text_field':
      // Connect controller
      const controllerRef = comp.id ? `controller: _controllers['${comp.id}'],` : '';
      return `TextField(
        ${controllerRef}
        decoration: InputDecoration(
            labelText: '${p.label}',
            hintText: '${p.hint}',
            filled: true,
            fillColor: AppTheme.surface,
            border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
        ),
        obscureText: ${p.obscure ? 'true' : 'false'},
        maxLines: ${p.multiline ? 5 : 1},
      ),SizedBox(height: 16),`;

    case 'list_tile':
        return `ListTile(
            tileColor: AppTheme.surface,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            leading: const Icon(Icons.${p.icon || 'star'}, color: AppTheme.primary),
            title: Text('${p.title}'),
            subtitle: Text('${p.subtitle}'),
            trailing: const Icon(Icons.chevron_right),
            onTap: () {},
        ),SizedBox(height: 8),`;

    case 'row':
        return `Row(
            spacing: 8,
            children: [
                ${(comp.children || []).map(c => 
                    // Recursively render children in row. Note: Row children usually need Expanded or Flexible if button
                    c.type === 'button' ? 'Expanded(child: ' + renderComponent(c).replace(',SizedBox(height: 12),', '') + ')' 
                    : renderComponent(c).replace(',SizedBox(height: 12),', '')
                ).join(',\n')}
            ],
        ),SizedBox(height: 12),`;

    case 'divider':
        return `const Divider(),SizedBox(height: 12),`;

    case 'app_bar':
        // Handled in Scaffold, not body
        return '';

    default:
      return `// Unknown: ${comp.type}`;
  }
};

const generateScreen = (screen, config) => {
    // Check if we need controllers (if text_fields exist)
    const hasTextFields = screen.components.some(c => c.type === 'text_field');
    const importServices = `import 'package:flutter/services.dart';`;

    const bodyWidgets = screen.components
        .filter(c => c.type !== 'app_bar')
        .map(renderComponent)
        .join("\n              ");

    const appBarComp = screen.components.find(c => c.type === 'app_bar');
    // Add Admin Icon if password is set and it's the first screen (or contains appbar)
    const adminAction = config.adminPassword && screen.id === config.screens[0].id
        ? `, actions: [IconButton(icon: const Icon(Icons.admin_panel_settings), onPressed: () => Navigator.pushNamed(context, '/admin_login'))]`
        : '';

    const appBarCode = appBarComp 
        ? `appBar: AppBar(title: Text('${appBarComp.props.title}'), centerTitle: ${appBarComp.props.centered}${adminAction}),`
        : '';

    const className = screen.id.charAt(0).toUpperCase() + screen.id.slice(1) + 'Screen';

    return `import 'package:flutter/material.dart';
import '../theme.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:share_plus/share_plus.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
${importServices}

class ${className} extends StatefulWidget {
  const ${className}({super.key});

  @override
  State<${className}> createState() => _${className}State();
}

class _${className}State extends State<${className}> {
  final Map<String, TextEditingController> _controllers = {};
  bool _loading = false;

  @override
  void initState() {
    super.initState();
    // Initialize controllers for text fields
    ${screen.components.filter(c => c.type === 'text_field').map(c => 
        `_controllers['${c.id}'] = TextEditingController();`
    ).join('\n    ')}
  }

  @override
  void dispose() {
    _controllers.forEach((_, controller) => controller.dispose());
    super.dispose();
  }

  Future<void> _handleAction(String action) async {
    if (action.startsWith('navigate:')) {
      // Navigate to route
      final target = action.split(':')[1];
      Navigator.pushNamed(context, '/$target');
    } else if (action.startsWith('share:')) {
      // Smart Share: Try to find 'output' field, else default
      String textToShare = "Check out my event!";
      if (_controllers.containsKey('output')) {
          textToShare = _controllers['output']!.text;
      }
      Share.share(textToShare);
    } else if (action.startsWith('copy:')) {
      // Smart Copy: Try to find 'output' field, else default
      String textToCopy = "Copied Content";
      if (_controllers.containsKey('output')) {
          textToCopy = _controllers['output']!.text;
      }
      
      Clipboard.setData(ClipboardData(text: textToCopy));
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Copied to clipboard!')),
      );
    } else if (action.startsWith('save_form:')) {
      // Collect data
      final data = _controllers.map((key, controller) => MapEntry(key, controller.text));
      
      setState(() => _loading = true);
      try {
        await Supabase.instance.client.from('registrations').insert({
          'app_name': '${config.name}',
          'data': data,
        });

        if (mounted) {
            showDialog(
                context: context,
                builder: (context) => AlertDialog(
                title: const Text('Success'),
                content: const Text('Registration Submitted!'),
                actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('OK'))],
                ),
            );
        }
      } catch (e) {
        if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
        }
      } finally {
        if (mounted) setState(() => _loading = false);
      }
    } else if (action.startsWith('ai:')) {
       setState(() => _loading = true);
       final type = action.split(':')[1].split('_')[1]; // e.g. generate_announcement -> announcement
       
       // Collect all form data
       final data = _controllers.map((key, controller) => MapEntry(key, controller.text));
       
       try {
         final url = Uri.parse('http://10.0.2.2:3000/api/ai-proxy');
         final response = await http.post(
            url, 
            headers: {'Content-Type': 'application/json'},
            body: jsonEncode({'type': type, 'data': data}),
         );

         if (response.statusCode == 200) {
             final result = jsonDecode(response.body)['result'];
             if (_controllers.containsKey('output')) {
                 _controllers['output']!.text = result;
             }
             if (mounted) {
               ScaffoldMessenger.of(context).showSnackBar(
                 const SnackBar(content: Text('AI Content Generated!')),
               );
             }
         } else {
             throw Exception('Failed to load AI response');
         }
       } catch (e) {
         if (mounted) {
            showDialog(
                context: context, 
                builder: (c) => AlertDialog(title: const Text('Error'), content: Text(e.toString()), actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('OK'))])
            );
         }
       } finally {
         setState(() => _loading = false);
       }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      ${appBarCode}
      body: Stack(
        children: [
          SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  ${bodyWidgets}
                ],
            ),
          ),
          if (_loading)
            const Positioned(
                top: 16,
                right: 16,
                child: Card(
                    elevation: 4,
                    shape: CircleBorder(),
                    child: Padding(
                        padding: EdgeInsets.all(8.0),
                        child: CircularProgressIndicator(strokeWidth: 3),
                    ),
                ),
            ),
        ],
      ),
    );
  }
}
`;
};

const generateAdminLogin = (config) => {
  return `import 'package:flutter/material.dart';
import '../theme.dart';

class AdminLoginScreen extends StatefulWidget {
  const AdminLoginScreen({super.key});

  @override
  State<AdminLoginScreen> createState() => _AdminLoginScreenState();
}

class _AdminLoginScreenState extends State<AdminLoginScreen> {
  final _passwordController = TextEditingController();

  void _login() {
    if (_passwordController.text == '${config.adminPassword}') {
      Navigator.pushReplacementNamed(context, '/admin_dashboard');
    } else {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Invalid Password')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Admin Access')),
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            TextField(
              controller: _passwordController,
              decoration: InputDecoration(
                labelText: 'Admin Password',
                filled: true,
                fillColor: AppTheme.surface,
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
              ),
              obscureText: true,
            ),
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _login,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppTheme.primary,
                  foregroundColor: Colors.white,
                  padding: const EdgeInsets.all(16),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                child: const Text('Login'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`;
};

const generateAdminDashboard = (config) => {
  return `import 'package:flutter/material.dart';
import '../theme.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class AdminDashboardScreen extends StatelessWidget {
  const AdminDashboardScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Admin Dashboard')),
      body: FutureBuilder<List<Map<String, dynamic>>>(
        future: Supabase.instance.client
            .from('registrations')
            .select()
            .eq('app_name', '${config.name}') 
            .limit(50)
            .order('created_at', ascending: false),
        builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
                return const Center(child: CircularProgressIndicator());
            }
            if (snapshot.hasError) {
                return Center(child: Text('Error: \${snapshot.error}'));
            }
            if (!snapshot.hasData || snapshot.data!.isEmpty) {
                return const Center(child: Text('No registrations yet'));
            }

            final registrations = snapshot.data!;
            
            return ListView.builder(
              padding: const EdgeInsets.all(16),
              itemCount: registrations.length,
              itemBuilder: (context, index) {
                final item = registrations[index];
                final data = item['data'] as Map<String, dynamic>;
                // Try to find common fields
                final name = data['name'] ?? 'Unknown';
                final email = data['email'] ?? 'No Email';
                final date = DateTime.parse(item['created_at']).toLocal().toString().split('.')[0];

                return Card(
                  color: AppTheme.surface,
                  margin: const EdgeInsets.only(bottom: 12),
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                  child: ListTile(
                    leading: CircleAvatar(
                      backgroundColor: AppTheme.primary.withOpacity(0.2),
                      child: Text(name[0].toUpperCase(), style: const TextStyle(color: AppTheme.primary)),
                    ),
                    title: Text(name),
                    subtitle: Text(email),
                    trailing: Text(date, style: const TextStyle(color: Colors.grey, fontSize: 12)),
                    onTap: () {
                        // Show full details
                        showDialog(
                            context: context,
                            builder: (c) => AlertDialog(
                                title: Text(name),
                                content: SingleChildScrollView(
                                    child: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: data.entries.map((e) => Padding(
                                            padding: const EdgeInsets.only(bottom: 8.0),
                                            child: Text('\${e.key}: \${e.value}', style: const TextStyle(fontSize: 14)),
                                        )).toList(),
                                    ),
                                ),
                                actions: [TextButton(onPressed: () => Navigator.pop(c), child: const Text('Close'))],
                            )
                        );
                    },
                  ),
                );
              },
            );
        }
      ),
    );
  }
}
`;
};

const generateAndroidManifest = (config) => {
  return `<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.example.app">
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <application
        android:label="${config.name}"
        android:name="\${applicationName}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>`;
};

/**
 * MAIN EXPORT
 * Returns a map of filenames to content
 */
export const generateFlutterProject = (config, supabaseUrl, supabaseKey) => {
  const files = {};

  // Root
  files['pubspec.yaml'] = generatePubspec(config);
  files['README.md'] = `# ${config.name}\nGenerated by WebsiteBuilder.`;
  files['.github/workflows/build.yml'] = generateWorkflow(config);
  
  // Android Manifest Overlay (to be copied by workflow)
  files['android_xml_overlay/AndroidManifest.xml'] = generateAndroidManifest(config);

  // Lib
  files['lib/main.dart'] = generateMain(config, supabaseUrl, supabaseKey);
// ... existing code ...
  files['lib/theme.dart'] = generateTheme(config);
  
  // Admin Screens
  if (config.adminPassword) {
      files['lib/screens/admin_login_screen.dart'] = generateAdminLogin(config);
      files['lib/screens/admin_dashboard_screen.dart'] = generateAdminDashboard(config);
  }

  // Screens
  config.screens.forEach(screen => {
      const filename = `lib/screens/${screen.id}_screen.dart`;
      files[filename] = generateScreen(screen, config);
  });

  return files;
};
