
import JSZip from "jszip";

/**
 * Build a ZIP buffer from a project file map.
 * @param {Object} files - Map of { "path/to/file.js": "file content string" }
 * @param {string} projectName - Name for the root folder
 * @returns {Promise<Buffer>} ZIP file as buffer
 */
export async function buildZip(files, projectName = "my-website") {
  const zip = new JSZip();
  const root = zip.folder(projectName);

  // Add README
  root.file("README.md", generateReadme(projectName));

  // Pre-process index.html to extract any embedded Base64 User Images into physical asset files
  let indexHtml = files["frontend/index.html"];
  if (indexHtml) {
    let imgCounter = 1;
    indexHtml = indexHtml.replace(/src="(data:image\/([^;]+);base64,([^"]+))"/g, (match, fullData, ext, base64) => {
      const fileName = `assets/custom_image_${imgCounter++}.${ext}`;
      // Write the physical binary to the zip
      root.file(`frontend/${fileName}`, base64, { base64: true });
      // Reroute the HTML tag to the physical file
      return `src="./${fileName}"`;
    });
    files["frontend/index.html"] = indexHtml;
  }

  // Add all remaining project files
  for (const [filePath, content] of Object.entries(files)) {
    root.file(filePath, content);
  }

  // Generate ZIP buffer
  const buffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 6 },
  });

  return buffer;
}

function generateReadme(projectName) {
  return `# ${projectName}

Generated by **AI Website Builder** 🚀

## Quick Start

### Development
1. Open \`frontend/index.html\` in any modern web browser.
2. For the best experience, use a local server like "Live Server" in VS Code.

### Backend
\`\`\`bash
cd backend
npm install
npm start
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── frontend/           # Vanilla HTML, CSS, and JS
│   ├── index.html      # Main page structure
│   ├── style.css       # Custom styles
│   ├── main.js        # Interactive logic
│   └── package.json    # Metadata
├── backend/            # Node.js + Express
│   ├── server.js       # Express server
│   ├── routes/         # API route handlers
│   └── package.json
└── README.md
\`\`\`

## Tech Stack

- **Frontend**: HTML5, CSS3 (Tailwind CSS via CDN), Vanilla JavaScript
- **Backend**: Node.js, Express
- **Animations**: CSS Transitions & Scroll-triggered Intersection Observer

## Environment Variables

Create a \`.env\` file in the backend directory:
\`\`\`
PORT=3001
FRONTEND_URL=http://localhost:5173
\`\`\`

---
*Built with ❤️ by AI Website Builder*
`;
}
